Models/BroadcastButton.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBot.Models
{
    public class CreateBroadCastModel
    {
        public class Button
        {
            public string type { get; set; }
            public string url { get; set; }
            public string title { get; set; }
        }

        public class Payload
        {
            public string template_type { get; set; }
            public string text { get; set; }
            public List<Button> buttons { get; set; }
        }

        public class Attachment
        {
            public string type { get; set; }
            public Payload payload { get; set; }
        }

        public class Message
        {
            public Attachment attachment { get; set; }
            public DynamicText dynamic_text { get; set; }
        }

        public class RootObject
        {
            public List<Message> messages { get; set; }

        }

        public class DynamicText
        {
            public string text { get; set; }
            public string fallback_text { get; set; }
        }
    }
}

Models/BroadcastModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBot.Models
{
    public class SendBroadcastModel
    {
        public string message_creative_id { get; set; }

        public string custom_label_id { get; set; }

        public string notification_type { get; set; }

        public string messaging_type { get; set; }

        public string tag { get; set; }
    }
}

Models/LabelModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBot.Models
{
    public class LabelModel
    {
        //labelname -> facebook -> labelid in DB
        public string name { get; set; }
        public string user { get; set; }
        public string psid { get; set; }
    }

    public class LabelData
    {
        public string name { get; set; }
        public string id { get; set; }
    }

    public class RootObject2
    {
        public List<LabelData> data { get; set; }
    }
}

Models/PageSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBot.Models
{
    public class PageSettings
    {
        public string PageId { get; set; } = "572005723217414";
        public string token { get; set; } = "EAAkmyGZAXK8MBAEtsTz2G4Xe46JSXmlvJ3Bn5hFK8wCTl2ZCVQ0Lmj9ehmwBSIb7lsFoOwHjzYgQsRvHPQOUHbRuoMv8xmBnZCiu0WYopgiXttLfpC157uzEjFroixzYBztaZBjNz06sx87KVD70ldxzMWRf6pa3a2SCZBdvFZCgZDZD";
        public string api { get; set; } = "https://tommotmot-testbotapi.herokuapp.com/";
    }
}

Models/SettingsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBot.Models
{
    public class SettingsViewModel
    {
        [Required(ErrorMessage = "Bitte gebe eine Nachricht ein!")]
        public string Message { get; set; }

        [Required(ErrorMessage = "Bitte gebe ein Call-To-Action ein!")]
        public string ButtonTextLive { get; set; }

        [Required(ErrorMessage = "Bitte gebe ein Call-To-Action ein!")]
        public string ButtonTextAufzeichnung { get; set; } = "Aufzeichnung?";
        public string Url { get; set; }
    }
}

Models/UserDBModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBot.Models
{
    public class UserDBModel
    {
        public string psid { get; set; }
        public string labelid { get; set; }
        public string username { get; set; }
       
    }
}

Controllers/BotController.cs
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Integration.AspNet.Core;

namespace Microsoft.BotBuilderSamples
{
    // This ASP Controller is created to handle a request. Dependency Injection will provide the Adapter and IBot
    // implementation at runtime. Multiple different IBot implementations running at different endpoints can be
    // achieved by specifying a more specific type for the bot constructor argument.
    [Route("api/messages")]
    [ApiController]
    public class BotController : ControllerBase
    {
        private readonly IBotFrameworkHttpAdapter _adapter;
        private readonly IBot _bot;

        public BotController(IBotFrameworkHttpAdapter adapter, IBot bot)
        {
            _adapter = adapter;
            _bot = bot;
        }

        [HttpPost]
        public async Task PostAsync()
        {
            // Delegate the processing of the HTTP POST to the adapter.
            // The adapter will invoke the bot.
            await _adapter.ProcessAsync(Request, Response, _bot);
        }
    }
}

Controllers/SettingsController.cs
using CoreBot.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace CoreBot.Controllers
{
    public class SettingsController : Controller
    {
        private Tuple<int, string> tuple;
        private Tuple<int, string> tuple2;

        [HttpGet]
        public IActionResult Index()
        {
            SettingsViewModel settings = new SettingsViewModel();
            settings.Message = "Test";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BroadcastAsync(SettingsViewModel settings)
        {
            PageSettings pageSettings = new PageSettings();

            if (ModelState.IsValid)
            {
                //check welche label es gibt
                Label label = new Label();
                tuple2 = await label.getAllLabels();

                if ((int)tuple2.Item1 == 200)
                {
                    //Checkt ob es schon ein Label gibt
                    var response = tuple2.Item2;
                    var labels = (RootObject2)Newtonsoft.Json.JsonConvert.DeserializeObject(response, typeof(RootObject2));

                    for (int i = 0; i < labels.data.Count; i++)
                    {
                        Broadcast broadcast = new Broadcast(pageSettings.token, pageSettings.PageId);
                        tuple = await broadcast.CreateBroadCastAsync(settings);

                        if ((int)tuple.Item1 == 200)
                        {
                            var message_id = tuple.Item2;

                            var jobj = (JObject)Newtonsoft.Json.JsonConvert.DeserializeObject(message_id);
                            var something = Uri.EscapeUriString(jobj["message_creative_id"].ToString());

                            await broadcast.SendBroadCastAsync(something, labels.data[i].id);
                        }
                    }
                }
                return Redirect("https://www.facebook.com/");
            }
            return View("Index");
        }
    }
}

Views/Settings/Index.cshtml
@model CoreBot.Models.SettingsViewModel

@{
    ViewData["Title"] = "Home Page";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @@media only screen and (min-width:1025px) {
            .customContainer {
                width: 500px;
                margin-left: auto;
                margin-right: auto;
            }
        }

        @@media only screen and (max-width:1028px) {
            .customContainer {
                width: 100%;
                padding-right: 15px;
                padding-left: 15px;
                margin-left: auto;
                margin-right: auto;
            }
        }

        .background {
            background-color: #E9EBEE;
        }

        .customNavBar {
            background-color: #4267B2;
            color:#FFFFFF;
        }

        .customNavItem:active {
            color: #FFFFFF;
        }

    </style>

</head>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>

<body class="background">
    <!-- A horizontal navbar that becomes vertical on small screens -->
    <nav class="navbar navbar-expand-sm customNavBar">
        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" style="color:#FFFFFF" href="@Url.Action("Index", "Settings")">Settings</a>
            </li>
        </ul>
    </nav>
    @using (Html.BeginForm("BroadCastAsync", "settings", FormMethod.Post))
    {
        <div class="customContainer">

            <form class="border border-light">
                <br />
                <br />
                <p class="h4 mb-4 p-10 pt-50">Neuen Livestream planen:</p>

                <!-- Message -->
                <div class="form-group">
                    @Html.TextAreaFor(m => m.Message, 3, 30, new { placeholder = "Message", @class = "form-control rounded-0" })
                    @Html.ValidationMessageFor(m => m.Message)
                </div>

                <!-- Button Live -->
                <div class="form-group">
                    @Html.TextBoxFor(m => m.ButtonTextLive, null, new { placeholder = "Call To Action (Live)", @class = "form-control mb-4" })
                    @Html.ValidationMessageFor(m => m.ButtonTextLive)
                </div>

                <!-- Button Aufzeichnung -->
                <div class="form-group">
                    @Html.TextBoxFor(m => m.ButtonTextLive, null, new { placeholder = "Call To Action (Aufzeichnung)", @class = "form-control mb-4" })
                    @Html.ValidationMessageFor(m => m.ButtonTextAufzeichnung)
                </div>

                <!-- Subject -->
                <input type="text" class="form-control mb-4" id="date" placeholder="Datum">

                <!-- Copy -->
                <input type="text" class="form-control mb-4" id="time" placeholder="Uhrzeit">

                <!-- Send button -->
                <button class="btn btn-info btn-block" value="Index" type="submit">Send</button>
            </form>
            <!-- Default form contact -->
        </div>
    }
    <script src="~/vendor.min.js"></script>
</body>

<link rel="stylesheet" href="@Url.Content("~/twitter-bootstrap/css/bootstrap.css")"/>

<script>
    $(document).ready(function () {
        $("#date").focus(function () {
            $(this).attr({ type: 'date' });
        });

        $("#time").focus(function () {
            $(this).attr({ type: 'time' });
        });
    });
</script>